version: '3'
services:
    web:
        image: nginx
        volumes:
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www:delegated
        ports:
            - ${EXTERNAL_WEB_PORT:-80}:80
        networks:
            - scrap-masters
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile-dev
            args:
                INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
        working_dir: /var/www
        user: ${CURRENT_UID:-1000}
        environment:
            - DOCKER=1
            - PHP_IDE_CONFIG=serverName=scrap-masters.local
        volumes:
            - .docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www:delegated
        ports:
            - ${EXTERNAL_PHP_PORT:-9000}:9000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db
            - redis
        networks:
            - scrap-masters
    db:
        image: postgres:13
        ports:
            - ${FORWARD_DB_PORT:-5432}:5432
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - /var/lib/postgresql/data
        networks:
            - scrap-masters
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:6'
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - ${EXTERNAL_REDIS_PORT:-6379}:6379
        volumes:
            - ./storage/redis:/data
        networks:
            - scrap-masters
# Networks
networks:
    scrap-masters:
        driver: bridge
